### ISSUE TITLE
Usage of runAsNonRoot is not compliant as per policy

### ISSUE THREAD

**Issue by ranjith-vatakkeel** [open-policy-agent/gatekeeper-library#117]
**What steps did you take and what happened:**

I am trying to implement `MustRunAsNonRoot` policy along with k8s spec `runAsNonRoot=true`. As per the [pod security standards ](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups) we can use either `runAsUser` or `runAsNonRoot`. We have `USER` directive defined in the image and trying to use `runAsNonRoot` so that we don't need to bound the k8s spec to the specific user ID. After this settings, pods are running with out root but policy is still reporting as pods are noncompliant resources.

**What did you expect to happen:**
  The policy should report as complaint

**Anything else you would like to add:**
Steps to reproduce:
1. Build sample image with a docker file with user directive 
2. Assign the policy along with k8s spec `spec.securityContext.runAsNonRoot: true`

**Environment:**

- Gatekeeper version:  v3.5.2
- Kubernetes version: (use `kubectl version`): v1.21.2

**Comment by maxsmythe** [comment]
re: the user directive...

unfortunately directives in the Dockerfile have no impact on admission requests, since there is no access to the contents of the image at admission time.

Can you tell us what rejection message is, and post an example constraint that rejects unexpectedly, along with an example object that should succeed that is causing an unexpected rejection?

**Comment by sozercan** [comment]
I believe PSP does this by talking to kubelet and CRI to get the image uid. As Max mentioned, unfortunately this information is not available for admission requests.

**Comment by maxsmythe** [comment]
@sozercan Does PSP operate outside the admission context?

**Comment by sozercan** [comment]
@maxsmythe sounds like it does, I thought that was interesting.
```
// In order to work properly this assumes that the kubelet performs a final check on runAsUser
// or the image UID when runAsUser is nil.
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/security/podsecuritypolicy/user/nonroot.go#L42-L43

**Comment by maxsmythe** [comment]
The comment is a bit unclear. Taking it in context with the code, I read it as saying assume the kubelet will enforce the UID restrictions if RunAsNonRoot is set. I don't think PSP itself is doing anything beyond analyzing the resource.

**Comment by ranjith-vatakkeel** [comment]
@maxsmythe Below is the sample violations message reported by the `CRD`  `K8sAzureAllowedUsersGroups`.
```
    - enforcementAction: dryrun
      kind: Pod
      message: 'Container rv-cli-rootd is attempting to run without a required securityContext/runAsUser.
        Allowed runAsUser: {"ranges": [], "rule": "MustRunAsNonRoot"}'
      name: rv-cli-rootd-844698896b-vgt7t
      namespace: default
```
If I am passing `spec.secuirtyContext.runAsUser` then policy is reporting as compliant but that will be like hardcoding the `UID` in the spec. Those are using distroless-images from Google would have to dig into which UID is used, and also that could change over time. So we were trying to work this with `runAsNonRoot`.
sample docker file
```
FROM mcr.microsoft.com/azure-cli
LABEL owner="RV"
RUN az --help 
RUN addgroup javagroup && adduser -D -G javagroup javauser
USER 1000
CMD ["sleep", "300"]
```
sample deployment spec
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rv-cli-rootd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rv-cli-rootd
  template:
    metadata:
      labels:
        app: rv-cli-rootd
    spec:
      containers:
      - image: sample.azurecr.io/rvcli:no-root-m
        name: rv-cli-rootd
        securityContext:
          allowPrivilegeEscalation: false
        resources:
      securityContext:
        runAsNonRoot: true
```
