### ISSUE TITLE
Allow specifying allowed images for disallowedtags

### ISSUE THREAD

**Issue by sathieu** [open-policy-agent/gatekeeper-library#120]
Allow to disallow all `latest` images, except a whitelist.

Expected usage:

 ```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowedTags
metadata:
  name: container-image-must-not-have-latest-tag
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    tags:
    - latest
    allowedImages:
    - foo/bar:latest
```
