### ISSUE TITLE
Can't enforce labels on deployments via kubectl edit

### ISSUE THREAD

**Issue by mkjmdski** [open-policy-agent/gatekeeper-library#122]
Hi :).

Hope somebody could help me with this. I have ContrainstTemplate as following (copied directly from this repo):

```yaml
# https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/requiredlabels/template.yaml
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
  annotations:
    description: Requires all resources to contain a specified label with a value
      matching a provided regular expression.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
            labels:
              type: array
              items:
                type: object
                properties:
                  key:
                    type: string
                  allowedRegex:
                    type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels
        get_message(parameters, _default) = msg {
          not parameters.message
          msg := _default
        }
        get_message(parameters, _default) = msg {
          msg := parameters.message
        }
        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_].key}
          missing := required - provided
          count(missing) > 0
          def_msg := sprintf("you must provide labels: %v", [missing])
          msg := get_message(input.parameters, def_msg)
        }
        violation[{"msg": msg}] {
          value := input.review.object.metadata.labels[key]
          expected := input.parameters.labels[_]
          expected.key == key
          # do not match if allowedRegex is not defined, or is an empty string
          expected.allowedRegex != ""
          not re_match(expected.allowedRegex, value)
          def_msg := sprintf("Label <%v: %v> does not satisfy allowed regex: %v", [key, value, expected.allowedRegex])
          msg := get_message(input.parameters, def_msg)
        }
```

I have following implementation of this template:

```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: pods-must-have-standard-labels
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds:
          - Deployment
          - DaemonSet
          - StatefulSet
          - Job
          - CronJob
          - Pod
  parameters:
    labels:
      - key: criticality
        regex: (critical|non-critical)
        # to get this, run: `echo replace(join("|", keys(module.common.group)), "_", "-") | terraform console` in some iam workspace after `terraform init`, for e.g. github.com/karhoo/terraform-iam/environments/common
      - key: team
        regex: (bots|business-operations|cloudops|core|ctrip|data|data-analytics|data-engineering|data-science|delivery|demand-mobile|demand-web|engineering-all|finance|finance-bigquery|iam|information-technology|karhoo-connect|marketing|marketpay|marketpay-x|marketpay-y|marketplace-performance|operational-finance|operations|operations-tooling|product|settlements|solution|technical-leadership)
      - key: version
      - key: app
```

Now I have used `kubectl edit` to modify one of the deployments that we have so it has following labels

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    deployment.kubernetes.io/revision: "3"
    karhoo.com/github-url: https://github.com/karhoo/karhoo-slack-bot
    meta.helm.sh/release-name: infrastructure-karhoo-slack-bot-worker
    meta.helm.sh/release-namespace: infra
  creationTimestamp: "2021-10-07T14:24:11Z"
  generation: 3
  labels:
    app: karhoo-slack-bot-worker
    app.kubernetes.io/managed-by: Helm
    chart: infrastructure-karhoo-slack-bot-worker
    criticality: non-critical
    heritage: Helm
    release: infrastructure-karhoo-slack-bot-worker
    type: infrastructure
...
```

As you can see it is missing `team` label. 

Now accoridng to the docs the following command: `kg K8sRequiredLabels pods-must-have-standard-labels -o json | jq '.status'` should show violations for the policy, however the output is following:

```json
{
  "auditTimestamp": "2021-10-13T12:55:39Z",
  "byPod": [
    {
      "constraintUID": "b7617ec6-a929-4d79-879c-4b6d64972dac",
      "enforced": true,
      "id": "gatekeeper-audit-6f5cd948df-d8x8l",
      "observedGeneration": 4,
      "operations": [
        "audit",
        "status"
      ]
    },
    {
      "constraintUID": "b7617ec6-a929-4d79-879c-4b6d64972dac",
      "enforced": true,
      "id": "gatekeeper-controller-manager-8465f8db98-k5hbj",
      "observedGeneration": 4,
      "operations": [
        "webhook"
      ]
    },
    {
      "constraintUID": "b7617ec6-a929-4d79-879c-4b6d64972dac",
      "enforced": true,
      "id": "gatekeeper-controller-manager-8465f8db98-qtcbl",
      "observedGeneration": 4,
      "operations": [
        "webhook"
      ]
    },
    {
      "constraintUID": "b7617ec6-a929-4d79-879c-4b6d64972dac",
      "enforced": true,
      "id": "gatekeeper-controller-manager-8465f8db98-scxrb",
      "observedGeneration": 4,
      "operations": [
        "webhook"
      ]
    }
  ],
  "totalViolations": 0
}
```

The OPA gatekeeper is deployed by helm with all settings as default
