### ISSUE TITLE
Mutation k8spspseccomp uses pathTests which is not supported for AssignMetadata

### ISSUE THREAD

**Issue by sathieu** [open-policy-agent/gatekeeper-library#123]
[library/experimental/mutation/pod-security-policy/seccomp/samples/mutation.yaml](https://github.com/open-policy-agent/gatekeeper-library/blob/010a40c3950cecf0cba322eddd485a41be267d2d/library/experimental/mutation/pod-security-policy/seccomp/samples/mutation.yaml):

```yaml
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: AssignMetadata
metadata:
  name: k8spspseccomp
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  location: metadata.annotations."seccomp.security.alpha.kubernetes.io/pod"
  parameters:
    pathTests:
    - subPath: metadata.annotations."seccomp.security.alpha.kubernetes.io/pod"
      condition: MustNotExist
    assign:
      value: runtime/default
```

Raises the following:

> error validating data: ValidationError(AssignMetadata.spec.parameters): unknown field "pathTests" in sh.gatekeeper.mutations.v1alpha1.AssignMetadata.spec.parameters

Ref: https://github.com/open-policy-agent/gatekeeper/blob/master/config/crd/bases/mutations.gatekeeper.sh_assignmetadata.yaml
