### ISSUE TITLE
Policy General, Required Labels - error message does not print the missing labels

### ISSUE THREAD

**Issue by stozinho** [open-policy-agent/gatekeeper-library#198]
I am making use of the ConstraintTemplate k8srequiredlabels 

My constraint has an array(map) of labels that it checks for. 

```
parameters:
    message: "All Deployments must have the following labels."
    labels: 
      - key: label1
      - key: label2
      - key: label3 
```

Looking at the rego in the ConstraintTemplate I would expect it to print the required, missing labels:

```
violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_].key}
          missing := required - provided
          count(missing) > 0
          def_msg := sprintf("you must provide labels: %v", [missing])
          msg := get_message(input.parameters, def_msg)
        }
```

However, all I see printed from the CLI is `"All Deployments must have the following labels."` 

Is my understanding correct here? In the example given there is only a single label checked for, so am I ok to check for multiple? 
And if my understanding is correct, does the rego need modifying so that it will actually print out the missing labels? 

Many thanks
