### ISSUE TITLE
is it possible to check fields directly in Pod spec?

### ISSUE THREAD

**Issue by rlisewski** [open-policy-agent/gatekeeper-library#22]
hello,
I'm a bit confused. Let say I have fields like below in Pod definition:
```
...
spec:
  automountServiceAccountToken: true
  containers:
...
```
I'm wondering if it's possible to create policy that can detect fields like that.
I started with something simple:
```
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sSATokenContainer
metadata:
  name: disallow-sa-token
spec:
  match:
    kinds:
      - apiGroups: ["v1"]
        kinds: ["Pod"]
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8ssatokencontainer
spec:
  crd:
    spec:
      names:
        kind: K8sSATokenContainer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8ssatokencontainer

        violation[{"msg": msg}] {
          input.review.kind.kind == "Pod"
          input.review.object.spec.automountServiceAccountToken == true
          msg := "Automount Service Account Token is not allowed"
        }
```
Pod can can still be created, am I missing something? Thanks in advance for any suggestions.

**Comment by maxsmythe** [comment]
It looks like the api group on the constraint match criteria might be wrong?

Because you are checking the kind in the constraint template, you can omit match kinds altogether. Does the following work:

```yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sSATokenContainer
metadata:
  name: disallow-sa-token
```

?
