### ISSUE TITLE
Gatekeeper Scanning and Validating Using Gatekeeper Constraints on  PodSecurityPolicy(PSP) Resource

### ISSUE THREAD

**Issue by sumanth-sure** [open-policy-agent/gatekeeper-library#221]
We are on Gatekeeper:3.9

As Gatekeeper Constraint Policies should apply on containers/Images As Stated Below. We have gatekeeper Running in AWS EKS Cluster:

```
Constraint:  **K8sPSPHostNamespace**
Disallows sharing of host PID and IPC namespaces by pod containers.
Corresponds to the `hostPID` and `hostIPC` fields in a PodSecurityPolicy For more information, see 
          
Constraint:  **k8spsphostnetworkingports**
Controls usage of host network namespace by pod containers. 
Specific ports must be specified. Corresponds to the `hostNetwork` and `hostPorts` fields in a PodSecurityPolicy.information
```
Our Setup:
We have a default PSP(PodSecurityPolicy) provided by AWS for Eks Cluster:
[link](https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html#:~:text=Amazon%20EKS%20default%20pod%20security%20policy)

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: privileged allows full unrestricted access to pod features,
      as if the PodSecurityPolicy controller was not enabled.
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    eks.amazonaws.com/component: pod-security-policy
    kubernetes.io/cluster-service: "true"
  name: eks.privileged
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
  ```
Which has following fields as true
```
  hostIPC: true
  hostNetwork: true
  hostPID: true
 ```
Problem:
**Gatekeeper is scanning and validating above PodSecurityPolicy Which is not a container/image and throwing validation errors**
Constraint:  K8sPSPHostNamespace psp-host-namespace
Log:
```
{"level":"info","ts":xxxx,"logger":"controller",
"msg":"Sharing the host namespace is not allowed: eks.privileged","process":"audit","audit_id":"xxxxx","details":{},"event_type":"violation_audited",
"constraint_group":"constraints.gatekeeper.sh",
"constraint_api_version":"v1beta1","constraint_kind":"K8sPSPHostNamespace",
"constraint_name":"psp-host-namespace","constraint_namespace":"",
"constraint_action":""
"deny","resource_group":"policy","resource_api_version":"v1beta1",
"resource_kind":"PodSecurityPolicy","resource_namespace":"","resource_name":"eks.privileged"}
```

<img width="1004" alt="Screenshot 2022-08-22 at 4 42 38 PM" src="https://user-images.githubusercontent.com/59997321/185908011-2a228531-1332-4705-8c5e-810c80b601d0.png">

Constraint: K8sPSPHostNetworkingPorts psp-host-network-ports
Log:
```
{"level":"info","ts":xxx,"logger":"controller",
"msg":"The specified hostNetwork and hostPort are not allowed, pod: eks.privileged. Allowed values: {\"hostNetwork\": false}","process":"audit","audit_id":"xxxxx",
"details{},"event_type":"violation_audited","constraint_group":"constraints.gatekeeper.sh","constraint_api_version":"v1beta1","constraint_kind":"K8sPSPHostNetworkingPorts","constraint_name":"psp-host-network-ports",
"constraint_namespace":"","constraint_action":"deny",
"resource_group":"policy","resource_api_version":
"v1beta1","resource_kind":"PodSecurityPolicy","resource_namespace":"","resource_name":"eks.privileged"}
```
<img width="1059" alt="Screenshot 2022-08-22 at 4 47 00 PM" src="https://user-images.githubusercontent.com/59997321/185908843-28678934-132a-49d8-8c45-c09f9afc35d6.png">

**We didn't get the validation error when we were in gatekeeper 3.1 Version.** how are we getting suddenly
How Gatekeeper is validating above resource
