### ISSUE TITLE
fix integration CI

### ISSUE THREAD

**Issue by sozercan** [open-policy-agent/gatekeeper-library#276]
looks like https://github.com/open-policy-agent/gatekeeper-library/pull/247 broke the integration tests

https://github.com/open-policy-agent/gatekeeper-library/actions/runs/3852491339/jobs/6578188623
```
# expected: created
# actual: Error from server (Forbidden): error when creating "library/general/poddisruptionbudget/samples/poddisruptionbudget/example_allowed_deployment4.yaml": admission webhook "validation.gatekeeper.sh" denied the request: [pod-distruption-budget] Deployment <nginx-deployment-allowed-4> has 1 replica(s) but PodDisruptionBudget <inventory-nginx-pdb-allowed-3> has minAvailable of 2, PodDisruptionBudget count should always be lower than replica(s), and not used when replica(s) is set to 1
```

**Comment by JaydipGabani** [comment]
@sozercan please assign this issue to me

**Comment by ctrought** [comment]
The label `example: allowed-deployment-3` omitted from the PDB was intentional, the specific test is to match on a subset of the labels and is what #247 fixed. The test was to cover this example. The same issue exists in #235, I think the inventory is not being destroyed between tests in CI. The tests pass on gator CLI so I'd imagine the fix needs to be implemented in the CI test itself?


```
  - name: example-allowed-subset-selector
    object: samples/poddisruptionbudget/example_allowed_deployment3.yaml
    inventory:
    - samples/poddisruptionbudget/example_inventory_allowed3.yaml
    assertions:
    - violations: no
```

Where example_inventory_allowed3.yaml

```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-nginx-pdb-allowed-3
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
```

Still selects this deployment example_allowed_deployment3.yaml that has additional labels (ie. `example: allowed-deployment-3`)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-allowed-3
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      example: allowed-deployment-3
  template:
    metadata:
      labels:
        app: nginx
        example: allowed-deployment-3
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
