### ISSUE TITLE
Not able to use allowedrepos and disallowedtags policies together

### ISSUE THREAD

**Issue by Anto450** [open-policy-agent/gatekeeper-library#304]
I can see allowedrepos repo policies override the disallowedtags policies.
I have created template and constraint for both the policies. 

My allowedrepos constraint policies.
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: repo-is-openpolicyagent
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "13e286349873.edt.ecr.us-east-2.amazonaws.com"
      - "96866989898.edt.ecr.us-east-2.amazonaws.com"
```
      
 When i try to create a pod it is not stoping me from creating the pod as i am creating the pod with latest tag which should result with "disallowed tag" error
kubectl run nginx --image=13e286349873.edt.ecr.us-east-2.amazonaws.com/nginx:latest --restart=Never

And also looks like we cannot use wildcard character in the repos list 
I wanted to allow all the repos which contains "edt.ecr.us-east-2.amazonaws.com" so that is allows all the aws account ecr registries.
tried to add wildcard to the prefix which is not working.

```
repos:
      - "*edt.ecr.us-east-2.amazonaws.com/"
```
      
Any help will be much appreciated.
