### ISSUE TITLE
enforcementAction: deny is not respected when creating/changing to an incorrect PDB

### ISSUE THREAD

**Issue by christiancarle-bakery** [open-policy-agent/gatekeeper-library#359]
I have a deployment with 2 replicas and a pdb with minAvailable: 1. I am using the official constraintTemplate and constraint for PDB.

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-test1-container-demo
  namespace: bakery-validate
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: container-demo
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-demo-deployment
  labels:
    app: container-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-demo
  template:
    metadata:
      labels:
        app: container-demo
    spec:
      containers:
      - name: container-demo
        image: christiancarle/containerdemo:test
        ports:
        - containerPort: 8080
```

When increasing minAvailable to 2 it is accepted even though I have `enforcementAction: deny`.
It throws the error but it still accept the change...
`- enforcementAction: deny
    group: apps
    kind: Deployment
    message: K8S1027 Deployment <container-demo-deployment> has 2 replica(s) but PodDisruptionBudget
      <pdb-test1-container-demo> has minAvailable of 2, PodDisruptionBudget count
      should always be lower than replica(s), and not used when replica(s) is set
      to 1
    name: container-demo-deployment
    namespace: bakery-validate
    version: v1
`

When I change the deployment to 1 replica the gatekeeper kicks in and declining the change of the deployment,
`admission webhook "validation.gatekeeper.sh" denied the request: [no-wrong-configured-pdbs] K8S1027 Deployment <container-demo-deployment> has 1 replica(s) but PodDisruptionBudget <pdb-test1-container-demo> has minAvailable of 2, PodDisruptionBudget count should always be lower than replica(s), and not used when replica(s) is set to 1`
