### ISSUE TITLE
Match everything in a constraint

### ISSUE THREAD

**Issue by asierraq** [open-policy-agent/gatekeeper-library#397]
Is there a configuration for `spec.match.kinds` in a constraint to match everything?

I've tried using a bunch of combinations, like this a one:

```yml
...
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["*"]
...
```

And none of them work. Is this even possible in OPA Gatekeeper?
