### ISSUE TITLE
Problem with creating a mutation for deployments

### ISSUE THREAD

**Issue by AleixoLucas42** [open-policy-agent/gatekeeper-library#401]
I'm sorry if this is not the platform where I can talk about this but, I'm trying to create a mutation that change the security context in the deployment, not in pod.

How i installed the gatekeeper:
> kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml
```
# My deployment example:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: busybox
        ports:
        - containerPort: 80
        command: [ "sh", "-c", "sleep 1h" ]
        
# My gatekeeper manifest:
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: gk-set-seccomp-profile-deployment
spec:
  applyTo:
  - groups: [""]
    kinds: ["Deployment"]
    versions: ["apps/v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Deployment"]
    namespaces: ["test"]
  location: "spec.template.spec.securityContext.seccompProfile"
  parameters:
    pathTests:
    - subPath: "spec.template.spec.securityContext.seccompProfile"
      condition: MustNotExist
    assign:
      value: 
        type: RuntimeDefault```


#When I do a mutation for pod works, but I can't make work with deployments.
#Any help is welcome (:

**Comment by AleixoLucas42** [comment]
> Does the replacement `versions: ["apps/v1"]` -> `versions: ["v1"]` fix things?

Nope, I've probably tried this before, but I did rn and does not work anyways (I've tried so many things that for sure somebody will think i'm crazy lol)

**Comment by apeabody** [comment]
Hi @AleixoLucas42 - I addition to @maxsmythe change to `versions: ["v1"]`, I believe `groups: [""]` -> `groups: ["apps"]`

Unlike `Pod` which is part of core `[""]`, `Deployment` is part of `["apps"]`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#deployment-v1-apps

**Comment by AleixoLucas42** [comment]
> Hi @AleixoLucas42 - In addition to @maxsmythe change to `versions: ["v1"]`, I believe `groups: [""]` -> `groups: ["apps"]`
> 
> Unlike `Pod` which is part of core `[""]`, `Deployment` is part of `["apps"]`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#deployment-v1-apps

I can't belive! I swear i tried this before...... Thanks a lot, you guys saved me a lot of time creating a script to patch more than 800 deployments (:

I tried these two and worked:
```
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: gk-set-privileged-false-deployment
spec:
  applyTo:
  - groups: ["apps"]
    kinds: ["Deployment"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Deployment"]
    namespaces: ["test"]
  location: "spec.template.spec.containers[name:*].securityContext.allowPrivilegeEscalation"
  parameters:
    pathTests:
    - subPath: "spec.template.spec.containers[name:*].securityContext.allowPrivilegeEscalation"
      condition: MustNotExist
    assign:
      value: false
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: gk-set-seccomp-profile-deployment
spec:
  applyTo:
  - groups: ["apps"]
    kinds: ["Deployment"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Deployment"]
    namespaces: ["test"]
  location: "spec.template.spec.securityContext.seccompProfile"
  parameters:
    pathTests:
    - subPath: "spec.template.spec.securityContext.seccompProfile"
      condition: MustNotExist
    assign:
      value: 
        type: RuntimeDefault
```
