### ISSUE TITLE
Update Config to include the latest Kubernetes 1.19 API group

### ISSUE THREAD

**Issue by JonnieDoe** [open-policy-agent/gatekeeper-library#42]
Update the ReplicateData config to include the latest Kubernetes 1.19 API group version for ingress.
```yaml
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
      - group: "networking.k8s.io"
        version: "v1beta1"
        kind: "Ingress"
     - group: "networking.k8s.io"
        version: "v1"
        kind: "Ingress"
```
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1-networking-k8s-io
https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/minimal-ingress.yaml
