### ISSUE TITLE
The example of disallowed/allowed ingress resources in the unique ingress host example has incorrect hostnames

### ISSUE THREAD

**Issue by WilliamRockwellEvans** [open-policy-agent/gatekeeper-library#484]
Link: https://open-policy-agent.github.io/gatekeeper-library/website/validation/uniqueingresshost/
The constraint template example uses a simple host_1 == host_2 logic, but the allowed and disallowed examples don't share the same host name -- accordingly the disallowed resource isn't blocked.

example-allowed:
example-allowed-host.example.com
example-allowed-host1.example.com

example-disallowed:
example-host.example.com

example-disallowed2:
example-host2.example.com
example-host3.example.com

**Comment by apeabody** [comment]
Hi Everyone!

There are three independent tests cases/samples, the resources aren't shared between them:

https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/suite.yaml
```
  - name: example-allowed
    object: samples/unique-ingress-host/example_allowed.yaml
    assertions:
    - violations: no
  - name: example-disallowed
    object: samples/unique-ingress-host/example_disallowed.yaml
    inventory:
    - samples/unique-ingress-host/example_inventory_disallowed.yaml
    assertions:
    - violations: yes
  - name: example-disallowed2
    object: samples/unique-ingress-host/example_disallowed2.yaml
    inventory:
    - samples/unique-ingress-host/example_inventory_disallowed2.yaml
    assertions:
    - violations: yes
```

example-allowed: (0 violations)
- [example-allowed-host.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_allowed.yaml#L8C11-L8C36)
- [example-allowed-host1.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_allowed.yaml#L18)

example-disallowed: (1 violation)
- [example-host.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_disallowed.yaml#L8C11-L8C36)
- [example-host.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_inventory_disallowed.yaml#L8C11-L8C36)

example-disallowed2: (1 violation)
- [example-host2.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_disallowed2.yaml#L8C11-L8C36)
- [example-host3.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_disallowed2.yaml#L18)
- [example-host2.example.com](https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/samples/unique-ingress-host/example_inventory_disallowed2.yaml#L8C11-L8C36)

@JaydipGabani - These tests appears to be working as intended to me, can you confirm?
