### ISSUE TITLE
Example k8scontainerlimits does not throw error for a deployment but does on a plain Pod creation

### ISSUE THREAD

**Issue by ujjwal-sophos** [open-policy-agent/gatekeeper-library#499]
Hi,
I was trying the example here from the link https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/general/containerlimits

It is working fine as per the core requirement by not allowing a Pod to run without defined limits for cpu and memory.
The problem is when I run a deployment yaml, the deployment apply is successful but the Pods don't come up which is expected.

When I just run the Pod.yaml it throws error and lets user know the problem. 
Is there way when applying a deployment yaml also it throws the error

e.g. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-pod
          image: arungupta/helloworld-spring-boot:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: hello-world

``` 
Doesn't throw error describe of the Deployment shows like this
<img width="747" alt="image" src="https://github.com/open-policy-agent/gatekeeper-library/assets/118428605/3f0388e6-b3b5-4e4c-a1fa-ee97f44ded49">

But when I just do a Pod deployment as this 
```

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  containers:
  - image: arungupta/helloworld-spring-boot:latest
    imagePullPolicy: Always
    name: hello-world-pod
    ports:
    - containerPort: 80
      protocol: TCP
```
It throws error properly like

<img width="1228" alt="image" src="https://github.com/open-policy-agent/gatekeeper-library/assets/118428605/64a39cd6-ed8d-4c72-9d9e-fd29162697aa">

Thanks in Advance
Ujjwal

**Comment by apeabody** [comment]
Hi @ujjwal-sophos!

The sample constraint above only applies to `Pod`, therefore it won't evaluate the `Deployment` when it is being created.  I would suggest you use an [ExpansionTemplate](https://open-policy-agent.github.io/gatekeeper/website/docs/expansion) to "expand" the deployment's template into a `Pod` for clearer evaluation.

For example, this expansion template should cause the deployment's template section to be evaluated as if it was a `Pod`:
```
apiVersion: expansion.gatekeeper.sh/v1alpha1
kind: ExpansionTemplate
metadata:
  name: expand-apps
spec:
  applyTo:
    - groups: ["apps"]
      kinds: ["DaemonSet", "Deployment", "ReplicaSet", "StatefulSet"]
      versions: ["v1"]
  templateSource: "spec.template"
  generatedGVK:
    kind: "Pod"
    group: ""
    version: "v1"
```

As you noted, even without the expansion template, your constraint will still apply when the `Deployment` attempt to (later) schedule pods.  But the expansion template will allow for better visibility at admission time when only the deployment itself is being created.
