### ISSUE TITLE
gMSA policy constraint for Windows Pods

### ISSUE THREAD

**Issue by jsturtevant** [open-policy-agent/gatekeeper-library#5]
**Describe the solution you'd like**
A policy in the library to apply a to apply a constraint on gMSA field in a Windows pod spec. 

A windows pod has a windowsOptions on the securityContext of the pod spec (and on the individual container):

```
spec:
      securityContext:
        windowsOptions:
          gmsaCredentialSpecName: gmsa-webapp1-crd
          gmsaCredentialSpec: <optional parameters if not using gmsaCrd>
```

In the case of using the [gmsa webhook and crd](https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/#install-webhooks-to-validate-gmsa-users) the gmsaCredentialSpec should not be set as the info is loaded from the CRD.

There could also be an option to have an AllowList of the gMSA CRD's that could be allowed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Gatekeeper version:
- Kubernetes version: (use `kubectl version`):
