### ISSUE TITLE
change to privileged: true otherwise disallowed pod still deploys

### ISSUE THREAD

**Issue by hilliao** [open-policy-agent/gatekeeper-library#53]
I propose changing https://github.com/open-policy-agent/gatekeeper-library/blob/2e5e92fecd750168ee1aaa833e17a24199e36a98/library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/example_disallowed.yaml#L12 to `        privileged: true` ; otherwise, the constraint still allows privileged pods to be created. 

```
# install gatekeeper agent
kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.2/deploy/gatekeeper.yaml
# install constraint template
kubectl apply -f https://github.com/open-policy-agent/gatekeeper-library/raw/master/library/pod-security-policy/privileged-containers/template.yaml
# installing the constraint
cat <<EOF | kubectl apply -f -
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: ns-hil-noroot
spec:
  match:
    kinds:
      - apiGroups: [ "" ]
        kinds: [ "Pod" ]
    namespaces: [ "hil" ]
EOF

# create the disallow pod succeeded
kubectl -n hil apply -f https://github.com/open-policy-agent/gatekeeper-library/raw/master/library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/example_disallowed.yaml
pod/nginx-privilege-escalation-disallowed created

gcloud container clusters describe asm-1 --zone=us-central1-f
addonsConfig:
  horizontalPodAutoscaling: {}
  httpLoadBalancing: {}
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
    disabled: true
autoscaling: {}
clusterIpv4Cidr: 10.108.0.0/14
createTime: '2021-01-28T01:02:18+00:00'
currentMasterVersion: 1.16.15-gke.6000
currentNodeCount: 4
currentNodeVersion: 1.16.15-gke.6000
databaseEncryption:
  state: DECRYPTED
defaultMaxPodsConstraint:
  maxPodsPerNode: '110'
```
