### ISSUE TITLE
tolerations & nodeselectors

### ISSUE THREAD

**Issue by kfox1111** [open-policy-agent/gatekeeper-library#86]
It would be great if there was a library to support similar functionalty to the alpha admission controllers:
* PodTolerationRestriction
* PodNodeSelector

**Comment by maxsmythe** [comment]
What alpha admission controller are you referencing? Can you expand on what `PodTolerationRestriction` and `PodNodeSelector` do/did?

**Comment by kfox1111** [comment]
They let you per namespace:
set a default set of tolerations / nodeSelectors to always add to pods if not already there. This lets you easily target pods automatically to pools of nodes. (Mutating webhook style)
Set an allowed set of tolerations / nodeSelectors that can be used. If others are used, they are denied. This prevents a user from using pools of nodes they don't have permissions to. (validating webhook style)

Both are listed here: 
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

**Comment by kfox1111** [comment]
The mutating webhooks in gatekeeper don't seem to have the nice librarization that the validating ones do. So for each pool, you'd need a complicated set of rules to make it work.

Probably need to add some kind of liberalization for mutating webhooks as well.

**Comment by kfox1111** [comment]
As a workaround, until librarization of mutating webhooks is possible, using a RuntimeClass for that seems to work ok:
```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: foo
handler: default
scheduling:
  nodeSelector:
    pool: foo
  tolerations:
  - key: "pool"
    operator: "Equal"
    value: "foo"
    effect: "NoSchedule"
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: foo-pool-assignment
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: pool
        operator: In
        values: [foo]
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.runtimeClassName"
  parameters:
    assign:
      value: userv1
```

Then you label nodes as pool=foo and namespaces as pool=foo

Still need a way to limit which nodeSelectors and tolerations are valid.
