### ISSUE TITLE
Please help with input.review.kind.kind and input.review.object.kind for ingress-whitelist.rego

### ISSUE THREAD

**Issue by AlexeyKukin** [open-policy-agent/gatekeeper-library#90]
Hello! 
Can someone explain me difference of:
input.review.object.kind == "Ingress"
https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/httpsonly/template.yaml

input.review.kind.kind == "Ingress"
https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/uniqueingresshost/template.yaml
I've googled too much but have no idea how corect.

Now I try do Gatekeeeper ConstraintTemplate for Ingress whitelist.
I have OPA rego rulle from step 4 of https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/
and try make gatekeeper ConstraintTemplate from it. Is it correct?:

```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8swhitelistingresshost
  annotations:
    description: Requires Ingress to be allowed in namespace.
spec:
  crd:
    spec:
      names:
        kind: K8sWhitelistIngressHost
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8swhitelistingresshost


        violation[{"msg": msg}] {
          input.review.kind.kind == "Ingress"
          host := input.review.object.spec.rules[_].host
          not fqdn_matches_any(host, valid_ingress_hosts)
          msg := sprintf("invalid ingress host %q", [host])
        }
        valid_ingress_hosts = {host |
          whitelist := namespaces[input.review.object.namespace].metadata.annotations["ingress-whitelist"]
          hosts := split(whitelist, ",")
          host := hosts[_]
        }
        fqdn_matches_any(str, patterns) {
          fqdn_matches(str, patterns[_])
        }
        fqdn_matches(str, pattern) {
          pattern_parts := split(pattern, ".")
          pattern_parts[0] == "*"
          str_parts := split(str, ".")
          n_pattern_parts := count(pattern_parts)
          n_str_parts := count(str_parts)
          suffix := trim(pattern, "*.")
          endswith(str, suffix)
        }
        fqdn_matches(str, pattern) {
          not contains(pattern, "*")
          str == pattern
        }
```
This give me error:
```
status:
  byPod:
  - errors:
    - code: ingest_error
      message: |-
        Could not ingest Rego: 2 errors occurred:
        __modset_templates["admission.k8s.gatekeeper.sh"]["K8sWhitelistIngressHost"]_idx_0:11: rego_unsafe_var_error: var namespaces is unsafe
        __modset_templates["admission.k8s.gatekeeper.sh"]["K8sWhitelistIngressHost"]_idx_0:13: rego_unsafe_var_error: var _ is unsafe
    id: gatekeeper-audit-787959864b-ps5fc
    observedGeneration: 1
    operations:
    - audit
    - status
    templateUID: 8124c61c-1a4c-49fe-9b86-e96dbfae4702
  - errors:
    - code: ingest_error
      message: |-
        Could not ingest Rego: 2 errors occurred:
        __modset_templates["admission.k8s.gatekeeper.sh"]["K8sWhitelistIngressHost"]_idx_0:11: rego_unsafe_var_error: var namespaces is unsafe
        __modset_templates["admission.k8s.gatekeeper.sh"]["K8sWhitelistIngressHost"]_idx_0:13: rego_unsafe_var_error: var _ is unsafe
    id: gatekeeper-controller-manager-59577d5c6c-cp6p2
    observedGeneration: 1
    operations:
    - webhook
    templateUID: 8124c61c-1a4c-49fe-9b86-e96dbfae4702

```

Is it possible implement ingress-whitelist.rego as ConstraintTemplate for gatekeeper?
