### ISSUE TITLE
Pod does not always get evaluated against the OPA policy

### ISSUE THREAD

**Issue by sreeprayagas** [open-policy-agent/gatekeeper-library#92]
Hello Team,

I have implemented the https://github.com/open-policy-agent/gatekeeper-library/tree/master/library/pod-security-policy/users gatekeeper library and edited it to only check for user ids. So, I removed the runAsGroup, supplementalGroups, fsGroups fields and their related functions.

I have an nginx file that is trying to run as user 1000

````
apiVersion: v1
kind: Pod
metadata:
  name: bad-nginx
  labels:
    app: bad-nginx
spec:
  containers:
[Archive.zip](https://github.com/open-policy-agent/gatekeeper-library/files/6819866/Archive.zip)

  - name: nginx
    image: nginx
    securityContext:
      runAsUser: 1000
      privileged: false
````

When I run the nginx file after applying the user ranges gatekeeper template, the pod's fields are evaluated against the OPA policy sometimes and sometimes the pod gets created.

Please look at this screenshot below.

<img width="1289" alt="Screen Shot 2021-07-15 at 12 04 55 pm" src="https://user-images.githubusercontent.com/87218892/125716705-82bddb02-9b69-40ea-aa83-a2d3ba7b374b.png">

I have attached all the files I am using (nginx, rego template and the constraint).

I am running AWS EKS 1.16.

Can anyone help me understand why this happens and how I can avoid this?
